[package]
name = "tornado-halo2"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_gadgets = "0.3.0"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git" }
rand = "0.8.5"
